# Generated by Django 4.2.1 on 2023-05-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('profile_image', models.ImageField(upload_to='client_profile_images')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('nationality', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('education_background', models.TextField()),
                ('preferred_contact', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('none', 'None')], max_length=10)),
            ],
        ),
    ]
